#!/usr/bin/env node
import {cpSync,existsSync,mkdirSync,readFileSync,readdirSync,rmSync,writeFileSync} from 'node:fs';import {dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
const ROOT=join(dirname(fileURLToPath(import.meta.url)),'..'),SRC=join(ROOT,'src'),DIST=join(ROOT,'dist'),APP_ID='activity-builder',CORE_VERSION='1.0.0',CORE_DIR=join(ROOT,'vendor',`ghrab-ai-core-${CORE_VERSION}`),CORE_FILE=`ghrab-ai-core-${CORE_VERSION}.js`,CORE_MANIFEST=`ghrab-ai-core-manifest-${CORE_VERSION}.json`,pkg=JSON.parse(readFileSync(join(ROOT,'package.json'),'utf8'));
const TOKENS={css:'/*==ACTIVA_STYLES==*/',body:'<!--==ACTIVA_BODY==-->',js:'/*==ACTIVA_JS==*/'},sha=f=>createHash('sha256').update(readFileSync(f)).digest('hex');for(const f of [CORE_FILE,CORE_MANIFEST])if(!existsSync(join(CORE_DIR,f)))throw new Error('Chybí '+f);const coreManifest=JSON.parse(readFileSync(join(CORE_DIR,CORE_MANIFEST),'utf8'));if(coreManifest.artifacts?.[CORE_FILE]?.sha256!==sha(join(CORE_DIR,CORE_FILE)))throw new Error('GHRAB AI Core neprošel SHA-256 kontrolou');
rmSync(DIST,{recursive:true,force:true});mkdirSync(DIST,{recursive:true});cpSync(SRC,DIST,{recursive:true});const tpl=readFileSync(join(DIST,'index.template.html'),'utf8'),css=readFileSync(join(DIST,'styles.css'),'utf8'),body=readFileSync(join(DIST,'body.html'),'utf8'),jsFiles=readdirSync(join(DIST,'js')).filter(n=>n.endsWith('.js')).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),appJs=jsFiles.map(n=>readFileSync(join(DIST,'js',n),'utf8')).join('\n;\n'),js=readFileSync(join(CORE_DIR,CORE_FILE),'utf8')+'\n;\n'+appJs;
let html=tpl.replace(TOKENS.css,()=>css).replace(TOKENS.body,()=>body).replace(TOKENS.js,()=>js).replaceAll('__APP_VERSION__',pkg.version).replaceAll('__BUILD_TIME__',new Date().toISOString());if(Object.values(TOKENS).some(t=>html.includes(t)))throw new Error('Build token zůstal ve výstupu');writeFileSync(join(DIST,'index.html'),html);for(const p of ['index.template.html','styles.css','body.html'])rmSync(join(DIST,p));rmSync(join(DIST,'js'),{recursive:true});
const operations=JSON.parse(readFileSync(join(DIST,'ai-operations.json'),'utf8'));if(operations.appId!==APP_ID||operations.appVersion!==pkg.version||operations.coreVersion!==CORE_VERSION||operations.operations.length!==1)throw new Error('Neplatný ai-operations.json');if(!appJs.includes('activity-pack-generation'))throw new Error('Chybí integrace AI operace');const manifest=JSON.parse(readFileSync(join(DIST,'studio-manifest.template.json'),'utf8').replaceAll('__APP_VERSION__',pkg.version).replaceAll('__BUILD_TIME__',new Date().toISOString()));if(manifest.aiCore?.coreVersion!==CORE_VERSION||manifest.aiCore?.serverReady!==true||manifest.aiCore?.conformancePassed!==true)throw new Error('studio-manifest nemá P1 AI Core metadata');writeFileSync(join(DIST,'studio-manifest.json'),JSON.stringify(manifest,null,2)+'\n');rmSync(join(DIST,'studio-manifest.template.json'));writeFileSync(join(DIST,'.nojekyll'),'');if(!existsSync(join(DIST,'manual','index.html'))||!existsSync(join(DIST,'tests','index.html')))throw new Error('Chybí manuál nebo testovací centrum');console.log(`[build] ACTIVA ${pkg.version}: Core ${CORE_VERSION} SHA-256 OK · ${jsFiles.length} modulů · dist připraven`);

// P2: canonical cross-application platform post-processing.
await import("./apply-ghrab-platform.mjs");
